title: My personal blog - Aniket Mehendale
email: aniket.mehendale204@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink:
baseurl: https://aniket204.github.io/blog # the subpath of your site, e.g. /blog
url: "https://aniket204.github.io/blog" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Aniket Mehendale # add your name
author-pic: adam-face.jpg
about-author: I’m a Computer Engineer. Know something of everything and everything of something.

# Contact links
email: aniket.mehendale204@gmail.com # Add your Email address
phone:  # Add your Phone number
website: https://github.com/Aniket204 # Add your website, do not add http://
linkedin: aniket-mehendale-880433104/ # Add your Linkedin handle
github: aniket204 # Add your Github handle
twitter: '@aniketmehendale' # Add your Twitter handle
facebook: aniket.mehendale.5 # Add your Facebook handle
instagram: aniketmehendale/ # Add your Instagram handle
pinterest: aniketmehendale/ # Add your Pinterest handle

# Newsletter
mailchimp: a1a4a978f4 # Add your MailChimp form identifier.


# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
